language: python
sudo: false
cache: pip
python:
- '3.4'
- '3.3'
- '2.7'
- '2.6'
env:
- DJANGO="django>=1.5.0,<1.6.0"
- DJANGO="django>=1.6.0,<1.7.0"
- DJANGO="django>=1.7.0,<1.8.0"
- DJANGO="django>=1.8.0,<1.9.0"
- DJANGO="django>=1.9.0,<1.10.0"
matrix:
  exclude:
  - python: '2.6'
    env: DJANGO="django>=1.7.0,<1.8.0"
  - python: '2.6'
    env: DJANGO="django>=1.8.0,<1.9.0"
  - python: '2.6'
    env: DJANGO="django>=1.9.0,<1.10.0"
  - python: '3.3'
    env: DJANGO="django>=1.4.0,<1.5.0"
  - python: '3.3'
    env: DJANGO="django>=1.9.0,<1.10.0"
before_install:
- pip install codecov
install:
  # Lower MarkDown version is needed for Python 2.6 only
- pip install -U pip wheel
- pip install -q $DJANGO django-wysiwyg html5lib==1.0b8 Pillow docutils textile MarkDown==2.4.1 -e .
script:
- coverage run --source=fluent_contents runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.freenode.org#django-fluent
    template:
    - '%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}'
    skip_join: true
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: CJ+oORfxdm/EQDbIbQ8VZmPLgA15wohO7tv5RpgZXnuTBIWrWE/DwGULqms8P6qiDgHyvR/S8g2wGdaS2HXdz/aDpPPfypyRJJu9y1mupuv1tG2NkN7+7qmjRhjTrn9vvo5I8GaEGKtGVh5jMeahsZkqrYykmLB9rsHoyhZwNmo=
    on_success: never
    on_failure: always
